/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package publicregistergroup.view;

import java.awt.Image;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.*;
import publicregistergroup.controller.ConnectionBuilder;
import publicregistergroup.model.Clubs;
import publicregistergroup.model.Enroll;
import publicregistergroup.model.Students;
import static publicregistergroup.view.LoginHomepage.con;

/**
 *
 * @author ART
 */
public class CheckAllActivity extends javax.swing.JFrame {

    static Connection con = ConnectionBuilder.getConnection();
    private static int clubIndex;
    DefaultListModel model = new DefaultListModel();
    private String stdName = Students.getStd_name(Login.getStdId());
    private String stdFaculty = Students.getStd_faculty(Login.getStdId());
    private String clubName = Clubs.getClub_name(getClubIndex());
    private String clubDescription = Clubs.getClub_description(getClubIndex());
    private int club_id = Clubs.getClub_id(getClubIndex());
    private long std_id = Login.getStdId();

    public static int getClubIndex() {
        return clubIndex +1;
    }

//    private String stdName = Students.getStd_name(Login.);
//    private String stdFaculty = Students.getStd_faculty(Login.getStdUserName());
    /**
     * Creates new form Homepage
     */
    public CheckAllActivity() {
        initComponents();
        setLocationRelativeTo(null);
        listJoinClubs.setModel(new javax.swing.AbstractListModel<String>() {
            ArrayList<String> strings = Enroll.getAllStudentsEnroll();

            @Override
            public int getSize() {
                return strings.size();
            }

            @Override
            public String getElementAt(int i) {
                return strings.get(i);
            }
        });
        
        jPanel2.setOpaque(false);
        Clubname.setVisible(false);
        Picture.setVisible(false);
        Club.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        Bottonsearch = new javax.swing.JButton();
        backbotton = new javax.swing.JButton();
        showName = new javax.swing.JLabel();
        showFaculty = new javax.swing.JLabel();
        เส้นขีดเฉยๆ = new javax.swing.JLabel();
        ลงทะเบียนชมรมแล้ว = new javax.swing.JLabel();
        formList = new javax.swing.JSplitPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        listJoinClubs = new javax.swing.JList<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        Clubname = new javax.swing.JLabel();
        Picture = new javax.swing.JLabel();
        Club = new javax.swing.JLabel();
        jlbClubId = new javax.swing.JLabel();
        AddName = new javax.swing.JLabel();
        AddDescription = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        blackground = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        jLabel6.setText("jLabel6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImages(getIconImages());
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 640, -1, 40));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 91, 261, 22));

        Bottonsearch.setFont(new java.awt.Font("Kanit", 0, 13)); // NOI18N
        Bottonsearch.setText("OK");
        Bottonsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BottonsearchActionPerformed(evt);
            }
        });
        getContentPane().add(Bottonsearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(286, 90, 80, 25));

        backbotton.setFont(new java.awt.Font("Quark", 0, 18)); // NOI18N
        backbotton.setText("Back");
        backbotton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbottonActionPerformed(evt);
            }
        });
        getContentPane().add(backbotton, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 630, 90, -1));

        showName.setFont(new java.awt.Font("Quark", 1, 30)); // NOI18N
        getContentPane().add(showName, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 230, 480, -1));
        showName.setText(stdName);

        showFaculty.setFont(new java.awt.Font("Quark", 0, 18)); // NOI18N
        getContentPane().add(showFaculty, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 262, 250, -1));
        showFaculty.setText(stdFaculty);

        เส้นขีดเฉยๆ.setText("_____________________________________________________________________________________________________________________________________");
        getContentPane().add(เส้นขีดเฉยๆ, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, 800, -1));

        ลงทะเบียนชมรมแล้ว.setFont(new java.awt.Font("Quark", 1, 20)); // NOI18N
        ลงทะเบียนชมรมแล้ว.setText("ลงทะเบียนชมรมแล้ว");
        getContentPane().add(ลงทะเบียนชมรมแล้ว, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 310, 148, -1));

        formList.setBorder(null);
        formList.setDividerLocation(252);
        formList.setDividerSize(2);

        listJoinClubs.setBackground(new java.awt.Color(253, 219, 160));
        listJoinClubs.setOpaque(false);
        listJoinClubs.setSelectionBackground(new java.awt.Color(247, 103, 63));
        listJoinClubs.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                listJoinClubsAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        listJoinClubs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listJoinClubsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                listJoinClubsMouseEntered(evt);
            }
        });
        listJoinClubs.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listJoinClubsValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(listJoinClubs);

        formList.setLeftComponent(jScrollPane2);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/RegisteredClubs.png"))); // NOI18N
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-70, 0, 540, 290));

        Clubname.setFont(new java.awt.Font("Quark", 1, 24)); // NOI18N
        Clubname.setText("ชมรมอาสาพัฒนาชุมชน");
        jPanel2.add(Clubname, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 230, 30));

        Picture.setBackground(new java.awt.Color(247, 247, 247));
        Picture.setFont(new java.awt.Font("Quark", 1, 70)); // NOI18N
        Picture.setForeground(new java.awt.Color(153, 153, 153));
        Picture.setText(" PIC");
        Picture.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Picture.setOpaque(true);
        jPanel2.add(Picture, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 150, 150));

        Club.setFont(new java.awt.Font("Quark", 1, 14)); // NOI18N
        Club.setText("<html> CLUB ID : <br>DESCRIPTION :  </html>");
        Club.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel2.add(Club, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, -1, 50));

        jlbClubId.setFont(new java.awt.Font("Quark", 0, 14)); // NOI18N
        jlbClubId.setText("0");
        jPanel2.add(jlbClubId, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 98, 60, 20));

        AddName.setFont(new java.awt.Font("Quark", 0, 14)); // NOI18N
        jPanel2.add(AddName, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 90, 110, 30));

        AddDescription.setFont(new java.awt.Font("Quark", 0, 14)); // NOI18N
        AddDescription.setText("    ข้อความ");
        AddDescription.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel2.add(AddDescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 120, 80));
        AddDescription.setText(clubDescription);

        jButton1.setBackground(new java.awt.Color(255, 63, 57));
        jButton1.setFont(new java.awt.Font("Quark", 0, 12)); // NOI18N
        jButton1.setText("UNJOIN");
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 80, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/bgRegisteredClubs.png"))); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-70, 0, 540, 290));

        formList.setRightComponent(jPanel2);

        getContentPane().add(formList, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 340, 720, 290));

        blackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/page.jpg"))); // NOI18N
        getContentPane().add(blackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BottonsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BottonsearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BottonsearchActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void backbottonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbottonActionPerformed
 String role = null;
        try {

            String sql = "SELECT * FROM students WHERE std_id = ?";
            PreparedStatement pre = con.prepareStatement(sql);
            pre.setLong(1, std_id);
            ResultSet res = pre.executeQuery();
            while (res.next()) {
                role = res.getString("std_role");
                System.out.println(role);
            }
        } catch (SQLException ex) {
            System.out.println(ex);
        }
        if (role.isEmpty()) {
            LinkDataforUser user = new LinkDataforUser();
            this.setVisible(false);
            user.setVisible(true);
        } else {
            LinkData admin = new LinkData();
            this.setVisible(false);
            admin.setVisible(true);
        }
    }//GEN-LAST:event_backbottonActionPerformed

    private void listJoinClubsAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_listJoinClubsAncestorAdded
        //clubIndex = listJoinClubs.getSelectedIndex();
         
    }//GEN-LAST:event_listJoinClubsAncestorAdded

    private void listJoinClubsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listJoinClubsMouseClicked
        clubIndex = listJoinClubs.getSelectedIndex();
        System.out.print(getClubIndex());
        jLabel4.setIcon(new javax.swing.ImageIcon());
        Clubname.setText(Clubs.getClub_name(getClubIndex()));
        jlbClubId.setText(getClubIndex()+"");
        AddDescription.setText(Clubs.getClub_description(getClubIndex()));
        Picture.setIcon(new ImageIcon((new ImageIcon("src/Images/"+(Clubs.getClub_pic(getClubIndex()))).getImage().getScaledInstance(150,150,Image.SCALE_SMOOTH))));
        
        Clubname.setVisible(true);
        Picture.setVisible(true);
        Club.setVisible(true);
       
        
        
    }//GEN-LAST:event_listJoinClubsMouseClicked

    private void listJoinClubsValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listJoinClubsValueChanged
        //clubIndex = listJoinClubs.getSelectedIndex();
    }//GEN-LAST:event_listJoinClubsValueChanged

    private void listJoinClubsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listJoinClubsMouseEntered

   
    }//GEN-LAST:event_listJoinClubsMouseEntered
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CheckAllActivity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CheckAllActivity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CheckAllActivity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CheckAllActivity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CheckAllActivity().setVisible(true);
                //jPanel1.setOpaque(false);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AddDescription;
    private javax.swing.JLabel AddName;
    private javax.swing.JButton Bottonsearch;
    private javax.swing.JLabel Club;
    private javax.swing.JLabel Clubname;
    private javax.swing.JLabel Picture;
    private javax.swing.JButton backbotton;
    private javax.swing.JLabel blackground;
    private javax.swing.JSplitPane formList;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel jlbClubId;
    private static javax.swing.JList<String> listJoinClubs;
    private javax.swing.JLabel showFaculty;
    private javax.swing.JLabel showName;
    private javax.swing.JLabel ลงทะเบียนชมรมแล้ว;
    private javax.swing.JLabel เส้นขีดเฉยๆ;
    // End of variables declaration//GEN-END:variables
}
