/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package publicregistergroup.view;
import java.awt.Image;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import publicregistergroup.controller.ConnectionBuilder;
import publicregistergroup.model.*;
import static publicregistergroup.view.ViewProfile.con;

/**
 *
 * @author ART
 */
public class Homepage extends javax.swing.JFrame {
    static Connection con = ConnectionBuilder.getConnection();
    private static int clubIndex;
    private String listClubs;
    DefaultListModel model = new DefaultListModel();
    private String search;
    

    public static int getClubIndex() {
        return clubIndex+1;
    }

    
    /**
     * Creates new form Homepage
     */

    public Homepage() {
        initComponents();
        setLocationRelativeTo(null);
        allClubs.setModel(new javax.swing.AbstractListModel<String>() {
            ArrayList<String> strings = Clubs.getAllClubs();
            @Override
            public int getSize() {
                return strings.size();
            }
            @Override
            public String getElementAt(int i) {
                return strings.get(i);
            }
        });
       jPanel1.setOpaque(false);
       jPanel2.setOpaque(false);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        searchclubTextField = new javax.swing.JTextField();
        Bottonsearch = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        allRecommend = new javax.swing.JTabbedPane();
        recommendPage1 = new javax.swing.JPanel();
        pic_P1 = new javax.swing.JLabel();
        clubName_P1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        clubId_P1 = new javax.swing.JLabel();
        des_P1 = new javax.swing.JLabel();
        joinClub_P1 = new javax.swing.JButton();
        recommendPage2 = new javax.swing.JPanel();
        pic_P2 = new javax.swing.JLabel();
        clubName_P2 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        clubId_P2 = new javax.swing.JLabel();
        des_P2 = new javax.swing.JLabel();
        joinClub_P2 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        pic_P3 = new javax.swing.JLabel();
        clubName_P3 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        clubId_P3 = new javax.swing.JLabel();
        des_P3 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        pic_P4 = new javax.swing.JLabel();
        clubName_P4 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        clubId_P4 = new javax.swing.JLabel();
        des_P4 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        allClubs = new javax.swing.JList<>();
        chooseClub = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        login = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        blackground = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();

        jLabel1.setText("jLabel1");

        jLabel6.setText("jLabel6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Homepage");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setIconImages(getIconImages());
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        searchclubTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchclubTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(searchclubTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 91, 261, 22));
        searchclubTextField.getAccessibleContext().setAccessibleDescription("");

        Bottonsearch.setFont(new java.awt.Font("Kanit", 0, 13)); // NOI18N
        Bottonsearch.setText("OK");
        Bottonsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BottonsearchActionPerformed(evt);
            }
        });
        getContentPane().add(Bottonsearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, 80, 25));

        allRecommend.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        allRecommend.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                allRecommendAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        recommendPage1.setBackground(new java.awt.Color(241, 232, 239));
        recommendPage1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        pic_P1.setFont(new java.awt.Font("Quark", 1, 65)); // NOI18N
        pic_P1.setForeground(new java.awt.Color(153, 153, 153));
        pic_P1.setText("   PIC");
        pic_P1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        clubName_P1.setFont(new java.awt.Font("Quark", 1, 20)); // NOI18N
        clubName_P1.setText("ชมรมอาสาพัฒนาชุมชน");

        jLabel9.setFont(new java.awt.Font("Quark", 1, 14)); // NOI18N
        jLabel9.setText("<html> CLUB ID :  <br>DESCRIPTION : </html>");
        jLabel9.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        clubId_P1.setText("  ");

        des_P1.setText("    ");
        des_P1.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        joinClub_P1.setFont(new java.awt.Font("Quark", 0, 14)); // NOI18N
        joinClub_P1.setText("สมัครเข้าร่วมชมรม");
        joinClub_P1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                joinClub_P1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout recommendPage1Layout = new javax.swing.GroupLayout(recommendPage1);
        recommendPage1.setLayout(recommendPage1Layout);
        recommendPage1Layout.setHorizontalGroup(
            recommendPage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(recommendPage1Layout.createSequentialGroup()
                .addGroup(recommendPage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(recommendPage1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(pic_P1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(recommendPage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(recommendPage1Layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(clubId_P1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(des_P1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(recommendPage1Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(clubName_P1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, recommendPage1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(joinClub_P1)
                .addGap(157, 157, 157))
        );
        recommendPage1Layout.setVerticalGroup(
            recommendPage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(recommendPage1Layout.createSequentialGroup()
                .addGroup(recommendPage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(recommendPage1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(clubName_P1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pic_P1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, recommendPage1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(recommendPage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(clubId_P1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(des_P1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(116, 116, 116)))
                .addComponent(joinClub_P1)
                .addGap(16, 16, 16))
        );

        pic_P1.setIcon(new ImageIcon((new ImageIcon("src/Images/"+(Clubs.getClub_pic(2))).getImage().getScaledInstance(229,272,Image.SCALE_SMOOTH))));
        clubName_P1.setText(Clubs.getClub_name(2));
        clubId_P1.setText(Clubs.getClub_id(2)+"");
        des_P1.setText(Clubs.getClub_description(2));

        allRecommend.addTab("", recommendPage1);

        recommendPage2.setBackground(new java.awt.Color(241, 232, 239));
        recommendPage2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        pic_P2.setFont(new java.awt.Font("Quark", 1, 65)); // NOI18N
        pic_P2.setForeground(new java.awt.Color(153, 153, 153));
        pic_P2.setText("   PIC");
        pic_P2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        clubName_P2.setFont(new java.awt.Font("Quark", 1, 20)); // NOI18N
        clubName_P2.setText("ชมรมอาสาพัฒนาชุมชน");

        jLabel12.setFont(new java.awt.Font("Quark", 1, 14)); // NOI18N
        jLabel12.setText("<html> CLUB ID :  <br>DESCRIPTION : </html>");
        jLabel12.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        clubId_P2.setText("  ");

        des_P2.setText("    ");
        des_P2.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        joinClub_P2.setFont(new java.awt.Font("Quark", 0, 14)); // NOI18N
        joinClub_P2.setText("สมัครเข้าร่วมชมรม");
        joinClub_P2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                joinClub_P2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout recommendPage2Layout = new javax.swing.GroupLayout(recommendPage2);
        recommendPage2.setLayout(recommendPage2Layout);
        recommendPage2Layout.setHorizontalGroup(
            recommendPage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(recommendPage2Layout.createSequentialGroup()
                .addGroup(recommendPage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(recommendPage2Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(pic_P2, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(recommendPage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(recommendPage2Layout.createSequentialGroup()
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(clubId_P2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(des_P2, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(recommendPage2Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(clubName_P2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, recommendPage2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(joinClub_P2)
                .addGap(157, 157, 157))
        );
        recommendPage2Layout.setVerticalGroup(
            recommendPage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(recommendPage2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(clubName_P2)
                .addGroup(recommendPage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(recommendPage2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pic_P2, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(recommendPage2Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(recommendPage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(clubId_P2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(des_P2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(joinClub_P2)
                .addGap(16, 16, 16))
        );

        pic_P2.setIcon(new ImageIcon((new ImageIcon("src/Images/"+(Clubs.getClub_pic(3))).getImage().getScaledInstance(229,272,Image.SCALE_SMOOTH))));
        clubName_P2.setText(Clubs.getClub_name(3));
        clubId_P2.setText(Clubs.getClub_id(3)+"");
        des_P2.setText(Clubs.getClub_description(3));

        allRecommend.addTab("", recommendPage2);

        jPanel7.setBackground(new java.awt.Color(241, 232, 239));
        jPanel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        pic_P3.setFont(new java.awt.Font("Quark", 1, 65)); // NOI18N
        pic_P3.setForeground(new java.awt.Color(153, 153, 153));
        pic_P3.setText("   PIC");
        pic_P3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        clubName_P3.setFont(new java.awt.Font("Quark", 1, 20)); // NOI18N
        clubName_P3.setText("ชมรมอาสาพัฒนาชุมชน");

        jButton6.setFont(new java.awt.Font("Quark", 0, 14)); // NOI18N
        jButton6.setText("สมัครเข้าร่วมชมรม");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Quark", 1, 14)); // NOI18N
        jLabel13.setText("<html> CLUB ID :  <br>DESCRIPTION : </html>");
        jLabel13.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        clubId_P3.setText("  ");

        des_P3.setText("    ");
        des_P3.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(pic_P3, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(clubId_P3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(des_P3, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(clubName_P3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton6)
                .addGap(157, 157, 157))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(clubName_P3)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pic_P3, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(clubId_P3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(des_P3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jButton6)
                .addGap(16, 16, 16))
        );

        pic_P3.setIcon(new ImageIcon((new ImageIcon("src/Images/"+(Clubs.getClub_pic(4))).getImage().getScaledInstance(229,272,Image.SCALE_SMOOTH))));
        clubName_P3.setText(Clubs.getClub_name(4));
        clubId_P3.setText(Clubs.getClub_id(4)+"");
        des_P3.setText(Clubs.getClub_description(4));

        allRecommend.addTab("", jPanel7);

        jPanel8.setBackground(new java.awt.Color(241, 232, 239));
        jPanel8.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        pic_P4.setBackground(new java.awt.Color(251, 236, 215));
        pic_P4.setFont(new java.awt.Font("Quark", 1, 65)); // NOI18N
        pic_P4.setForeground(new java.awt.Color(153, 153, 153));
        pic_P4.setText("   PIC");
        pic_P4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        clubName_P4.setFont(new java.awt.Font("Quark", 1, 20)); // NOI18N
        clubName_P4.setText("ชมรมอาสาพัฒนาชุมชน");

        jButton7.setFont(new java.awt.Font("Quark", 0, 14)); // NOI18N
        jButton7.setText("สมัครเข้าร่วมชมรม");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Quark", 1, 14)); // NOI18N
        jLabel14.setText("<html> CLUB ID :  <br>DESCRIPTION : </html>");
        jLabel14.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        clubId_P4.setText("  ");

        des_P4.setText("    ");
        des_P4.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(pic_P4, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(clubId_P4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(des_P4, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(clubName_P4)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton7)
                .addGap(157, 157, 157))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(clubName_P4)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pic_P4, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(clubId_P4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(des_P4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jButton7)
                .addGap(16, 16, 16))
        );

        pic_P4.setIcon(new ImageIcon((new ImageIcon("src/Images/"+(Clubs.getClub_pic(5))).getImage().getScaledInstance(229,272,Image.SCALE_SMOOTH))));
        clubName_P4.setText(Clubs.getClub_name(5));
        clubId_P4.setText(Clubs.getClub_id(5)+"");
        des_P4.setText(Clubs.getClub_description(5));

        allRecommend.addTab("", jPanel8);

        jLabel11.setFont(new java.awt.Font("Quark", 1, 24)); // NOI18N
        jLabel11.setText("ชมรมแนะนำ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(allRecommend, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 12, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(allRecommend, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 490, 430));

        allClubs.setFont(new java.awt.Font("Quark", 0, 16)); // NOI18N
        allClubs.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                allClubsAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        allClubs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                allClubsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(allClubs);

        chooseClub.setFont(new java.awt.Font("Quark", 0, 13)); // NOI18N
        chooseClub.setText(" Click");
        chooseClub.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chooseClubMouseClicked(evt);
            }
        });
        chooseClub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseClubActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Quark", 1, 18)); // NOI18N
        jLabel2.setText("ชมรมทั้งหมด");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 440, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(357, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(chooseClub))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(chooseClub))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 210, 440, -1));

        login.setFont(new java.awt.Font("Quark", 0, 18)); // NOI18N
        login.setIcon(new javax.swing.ImageIcon("C:\\Users\\kz_no\\Desktop\\ProjectPublicRegister\\src\\Images\\login.png")); // NOI18N
        login.setBorder(null);
        login.setBorderPainted(false);
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        getContentPane().add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 20, 30, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("LOGIN");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(959, 55, 40, -1));
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 640, -1, 40));

        blackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/page.jpg"))); // NOI18N
        getContentPane().add(blackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(-5, 0, 1030, 770));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 30, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BottonsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BottonsearchActionPerformed
        search = searchclubTextField.getText();
        String club="";    
        try {
            
           
            String sql = "SELECT * FROM clubs where club_name LIKE '%"+search+"%'";
            PreparedStatement pre = con.prepareStatement(sql);
//            pre.setString(1, "%"+search+"%");
            System.out.println(search+" search la");
             ResultSet res = pre.executeQuery();
             System.out.println("EXE LAEW");
                if(res.next()) {
                    club =res.getString("club_name");
                    System.out.println(club+" clubname");
                }
                
        } catch (SQLException ex) {
            ex.printStackTrace();
        }if (search .equals(club)) {
            JOptionPane frame = new JOptionPane();
            JOptionPane.showMessageDialog(frame,"Search success","Search club",JOptionPane.PLAIN_MESSAGE);
             // = allClubs.getSelectedIndex();
             ViewClubFromSearch view = new ViewClubFromSearch();
            this.setVisible(false);
             view.setVisible(true);
        }
        else {
            JOptionPane frame = new JOptionPane();
            JOptionPane.showMessageDialog(frame,"Failed club name","Search club",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_BottonsearchActionPerformed

    private void searchclubTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchclubTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchclubTextFieldActionPerformed

    private void joinClub_P1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_joinClub_P1ActionPerformed
       ViewRegist view = new ViewRegist();
       this.setVisible(false);
       view.setVisible(true);
    }//GEN-LAST:event_joinClub_P1ActionPerformed

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        // TODO add your handling code here:
        Login log = new Login();
        this.setVisible(false);
        log.setVisible(true);
        log.pack();
    }//GEN-LAST:event_loginActionPerformed

    private void joinClub_P2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_joinClub_P2ActionPerformed
       ViewRegist view = new ViewRegist();
       this.setVisible(false);
       view.setVisible(true);
    }//GEN-LAST:event_joinClub_P2ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
       ViewRegist view = new ViewRegist();
       this.setVisible(false);
       view.setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
       ViewRegist view = new ViewRegist();
       this.setVisible(false);
       view.setVisible(true);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void allClubsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_allClubsMouseClicked
        /*try {
            // TODO add your handling code here:
            //allClubs.getModel();
            //name = NameTextField.getText();
            //faculty = SurnameTextField.getText();
            //telephone = TelephoneTextField.getText();
            //facebook = FacebookTextField.getText();
            //medicineloss = MedicineTextField.getText();
            //foodloss = FoodTextField.getText();
            //email = EmailTextField.getText();
            Statement st = con.createStatement();
            String sql = "SELECT * FROM clubs order by club_id ASC";
            PreparedStatement pre = con.prepareStatement(sql);
            //pre.setString(1, name);
            //pre.setString(2, faculty);
            //pre.setString(3, telephone);
            ResultSet res = pre.executeQuery();
            //ResultSet res = st.executeQuery(sql);
            int row = 0;
            while((res!=null) && (res.next())){
                model.addElement(res.getInt("club_id") + "  " + res.getString("club_name"));
            }
            res.close();
            con.close();
        } catch (SQLException ex) {
            System.out.println(ex);
            System.out.println(ex.getMessage());
        }
        catch (Exception ex) {
            System.out.println(ex.getMessage());
        }
        */
        /*ViewClub view = new ViewClub();
        this.setVisible(false);
        view.setVisible(true);*/

    }//GEN-LAST:event_allClubsMouseClicked

    private void allClubsAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_allClubsAncestorAdded



    }//GEN-LAST:event_allClubsAncestorAdded

    private void chooseClubMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chooseClubMouseClicked

    }//GEN-LAST:event_chooseClubMouseClicked

    private void chooseClubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseClubActionPerformed
        //JOptionPane.showMessageDialog(null,"You selected : " + allClubs.getSelectedValue());
        clubIndex = allClubs.getSelectedIndex();
        //System.out.println(clubIndex);
        ViewClubBeforeLogin viewclub = new ViewClubBeforeLogin();
        this.setVisible(false);
        viewclub.setVisible(true);
    }//GEN-LAST:event_chooseClubActionPerformed

    private void allRecommendAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_allRecommendAncestorAdded
      
    }//GEN-LAST:event_allRecommendAncestorAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Homepage().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bottonsearch;
    private javax.swing.JList<String> allClubs;
    private javax.swing.JTabbedPane allRecommend;
    private javax.swing.JLabel blackground;
    private javax.swing.JButton chooseClub;
    private javax.swing.JLabel clubId_P1;
    private javax.swing.JLabel clubId_P2;
    private javax.swing.JLabel clubId_P3;
    private javax.swing.JLabel clubId_P4;
    private javax.swing.JLabel clubName_P1;
    private javax.swing.JLabel clubName_P2;
    private javax.swing.JLabel clubName_P3;
    private javax.swing.JLabel clubName_P4;
    private javax.swing.JLabel des_P1;
    private javax.swing.JLabel des_P2;
    private javax.swing.JLabel des_P3;
    private javax.swing.JLabel des_P4;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private static javax.swing.JPanel jPanel1;
    private static javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton joinClub_P1;
    private javax.swing.JButton joinClub_P2;
    private javax.swing.JButton login;
    private javax.swing.JLabel pic_P1;
    private javax.swing.JLabel pic_P2;
    private javax.swing.JLabel pic_P3;
    private javax.swing.JLabel pic_P4;
    private javax.swing.JPanel recommendPage1;
    private javax.swing.JPanel recommendPage2;
    private javax.swing.JTextField searchclubTextField;
    // End of variables declaration//GEN-END:variables
}
