/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package publicregistergroup.view;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import static publicregistergroup.view.ViewProfile.con;

/**
 *
 * @author taloey
 */
public class LinkDataforUser extends javax.swing.JFrame {
private String search;
    /**
     * Creates new form Uploadphoto
     */
    public LinkDataforUser() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        searchTextField = new javax.swing.JTextField();
        Bottonsearch = new javax.swing.JButton();
        UsernameID = new javax.swing.JLabel();
        Box1 = new javax.swing.JPanel();
        changeprofilebotton = new javax.swing.JButton();
        Box2 = new javax.swing.JPanel();
        checkclubbotton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        Backbotton = new javax.swing.JButton();
        blackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        searchTextField.setMinimumSize(new java.awt.Dimension(8, 22));
        searchTextField.setPreferredSize(new java.awt.Dimension(8, 22));
        searchTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(searchTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 91, 261, 22));

        Bottonsearch.setFont(new java.awt.Font("Kanit", 0, 13)); // NOI18N
        Bottonsearch.setText("OK");
        Bottonsearch.setMaximumSize(new java.awt.Dimension(55, 30));
        Bottonsearch.setMinimumSize(new java.awt.Dimension(55, 30));
        Bottonsearch.setPreferredSize(new java.awt.Dimension(55, 30));
        Bottonsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BottonsearchActionPerformed(evt);
            }
        });
        getContentPane().add(Bottonsearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, 80, 25));

        UsernameID.setFont(new java.awt.Font("Kanit", 0, 24)); // NOI18N
        getContentPane().add(UsernameID, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 40, 220, 30));

        Box1.setBackground(new java.awt.Color(77, 77, 77));
        Box1.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(205, 77, 40)));

        changeprofilebotton.setFont(new java.awt.Font("Quark", 0, 48)); // NOI18N
        changeprofilebotton.setForeground(new java.awt.Color(204, 204, 204));
        changeprofilebotton.setText("แก้ไขข้อมูลส่วนตัว");
        changeprofilebotton.setBorder(null);
        changeprofilebotton.setContentAreaFilled(false);
        changeprofilebotton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        changeprofilebotton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        changeprofilebotton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeprofilebottonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Box1Layout = new javax.swing.GroupLayout(Box1);
        Box1.setLayout(Box1Layout);
        Box1Layout.setHorizontalGroup(
            Box1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Box1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(changeprofilebotton, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        Box1Layout.setVerticalGroup(
            Box1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Box1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(changeprofilebotton, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(Box1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 290, 480, 90));

        Box2.setBackground(new java.awt.Color(77, 77, 77));
        Box2.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(205, 77, 40)));

        checkclubbotton.setFont(new java.awt.Font("Quark", 0, 48)); // NOI18N
        checkclubbotton.setForeground(new java.awt.Color(204, 204, 204));
        checkclubbotton.setText("เช็ค club activities");
        checkclubbotton.setBorder(null);
        checkclubbotton.setContentAreaFilled(false);
        checkclubbotton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        checkclubbotton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkclubbottonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Box2Layout = new javax.swing.GroupLayout(Box2);
        Box2.setLayout(Box2Layout);
        Box2Layout.setHorizontalGroup(
            Box2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Box2Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(checkclubbotton, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        Box2Layout.setVerticalGroup(
            Box2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Box2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(checkclubbotton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        getContentPane().add(Box2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 450, 480, 90));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 640, 400, 40));

        Backbotton.setText("Back");
        Backbotton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackbottonActionPerformed(evt);
            }
        });
        getContentPane().add(Backbotton, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 140, 150, 40));

        blackground.setIcon(new javax.swing.ImageIcon("/Users/taloey/Desktop/PublicRegister/src/Images/page.jpg")); // NOI18N
        blackground.setText("jLabel1");
        getContentPane().add(blackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(-5, 0, 1030, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BottonsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BottonsearchActionPerformed
        search = searchTextField.getText();
        String club="";    
        try {
            
           
            String sql = "SELECT * FROM clubs where club_name LIKE '%"+search+"%'";
            PreparedStatement pre = con.prepareStatement(sql);
//            pre.setString(1, "%"+search+"%");
            System.out.println(search+" search la");
             ResultSet res = pre.executeQuery();
             System.out.println("EXE LAEW");
                if(res.next()) {
                    club =res.getString("club_name");
                    System.out.println(club+" clubname");
                }
                
        } catch (SQLException ex) {
            ex.printStackTrace();
        }if (search .equals(club)) {
            JOptionPane frame = new JOptionPane();
            JOptionPane.showMessageDialog(frame,"Search success","Search club",JOptionPane.PLAIN_MESSAGE);
             // = allClubs.getSelectedIndex();
             ViewClubFromSearch view = new ViewClubFromSearch();
            this.setVisible(false);
             view.setVisible(true);
        }
        else {
            JOptionPane frame = new JOptionPane();
            JOptionPane.showMessageDialog(frame,"Failed club name","Search club",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_BottonsearchActionPerformed

    private void checkclubbottonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkclubbottonActionPerformed
     CheckAllActivity check = new CheckAllActivity();
       this.setVisible(false);
       check.setVisible(true);
    }//GEN-LAST:event_checkclubbottonActionPerformed

    private void changeprofilebottonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeprofilebottonActionPerformed
      ViewProfile profile = new ViewProfile();
       this.setVisible(false);
       profile.setVisible(true);
    }//GEN-LAST:event_changeprofilebottonActionPerformed

    private void searchTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchTextFieldActionPerformed

    private void BackbottonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackbottonActionPerformed
        this.setVisible(false);
            LoginHomepage login = new LoginHomepage();
            login.setVisible(true);
    }//GEN-LAST:event_BackbottonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LinkDataforUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LinkDataforUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LinkDataforUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LinkDataforUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LinkDataforUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Backbotton;
    private javax.swing.JButton Bottonsearch;
    private javax.swing.JPanel Box1;
    private javax.swing.JPanel Box2;
    private javax.swing.JLabel UsernameID;
    private javax.swing.JLabel blackground;
    private javax.swing.JButton changeprofilebotton;
    private javax.swing.JButton checkclubbotton;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField searchTextField;
    // End of variables declaration//GEN-END:variables
}
