/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package publicregistergroup.view;

import java.sql.Connection;
import publicregistergroup.controller.ConnectionBuilder;
import publicregistergroup.model.*;


/**
 *
 * @author kz_no
 */
public class ViewRegist extends javax.swing.JFrame {
    static Connection con = ConnectionBuilder.getConnection();
    private String clubName = Clubs.getClub_name(Homepage.getClubIndex());
    //private String clubDescription = Clubs.getClub_description(Homepage.getClubIndex());
    private int club_id = Clubs.getClub_id(Homepage.getClubIndex());
    
    private long stdID = Students.getStd_id(Login.getStdUserName());
    private String stdName = Students.getStd_name(stdID);
    private String stdTel = Students.getStd_tel(stdID);
    private String stdFacebook = Students.getStd_facebook(stdID);
    private String stdMedicine = Students.getStd_medicine(stdID);
    private String stdFood = Students.getStd_food(stdID);
    private String stdEmail = Students.getStd_email(stdID);
    
    
    
    
    /**
     * Creates new form ViewRegist
     */
    public ViewRegist() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NameClub = new javax.swing.JLabel();
        ClubID = new javax.swing.JLabel();
        ShowClubID = new javax.swing.JLabel();
        เส้นขีดเฉยๆ = new javax.swing.JLabel();
        pic = new javax.swing.JLabel();
        Name = new javax.swing.JLabel();
        AnsName = new javax.swing.JLabel();
        Telephone = new javax.swing.JLabel();
        AnsTelephone = new javax.swing.JLabel();
        Facebook = new javax.swing.JLabel();
        AnsFacebook = new javax.swing.JLabel();
        แพ้ยาอะไร = new javax.swing.JLabel();
        AnsMedicine = new javax.swing.JLabel();
        แพ้อาหาอะไร = new javax.swing.JLabel();
        AnsFood = new javax.swing.JLabel();
        Email = new javax.swing.JLabel();
        AnsEmail = new javax.swing.JLabel();
        ID = new javax.swing.JLabel();
        ShowID = new javax.swing.JLabel();
        Edit = new javax.swing.JButton();
        Confirm = new javax.swing.JButton();
        blackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1024, 768));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        NameClub.setFont(new java.awt.Font("Quark", 1, 32)); // NOI18N
        getContentPane().add(NameClub, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 490, 40));
        NameClub.setText(Clubs.getClub_name(club_id));

        ClubID.setFont(new java.awt.Font("Quark", 0, 14)); // NOI18N
        ClubID.setText("CLUB ID : ");
        getContentPane().add(ClubID, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, -1, -1));

        ShowClubID.setFont(new java.awt.Font("Quark", 0, 14)); // NOI18N
        getContentPane().add(ShowClubID, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, 260, 20));
        ShowClubID.setText(club_id+"");

        เส้นขีดเฉยๆ.setText("____________________________________________________________________________________________________________");
        getContentPane().add(เส้นขีดเฉยๆ, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 650, -1));

        pic.setFont(new java.awt.Font("Quark", 1, 72)); // NOI18N
        pic.setForeground(new java.awt.Color(153, 153, 153));
        pic.setText("    PIC");
        pic.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(pic, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 274, 277));

        Name.setFont(new java.awt.Font("Quark", 1, 16)); // NOI18N
        Name.setText("Name :");
        getContentPane().add(Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 260, -1, -1));

        AnsName.setFont(new java.awt.Font("Quark", 0, 16)); // NOI18N
        AnsName.setText(" ");
        getContentPane().add(AnsName, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 260, 420, -1));
        AnsName.setText(Students.getStd_name(stdID));

        Telephone.setFont(new java.awt.Font("Quark", 1, 16)); // NOI18N
        Telephone.setText("Telephone :");
        getContentPane().add(Telephone, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 290, -1, -1));

        AnsTelephone.setFont(new java.awt.Font("Quark", 0, 16)); // NOI18N
        AnsTelephone.setText(" ");
        getContentPane().add(AnsTelephone, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 280, 270, 30));
        AnsTelephone.setText(Students.getStd_tel(stdID));

        Facebook.setFont(new java.awt.Font("Quark", 1, 16)); // NOI18N
        Facebook.setText("Facebook :");
        getContentPane().add(Facebook, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 320, -1, -1));

        AnsFacebook.setFont(new java.awt.Font("Quark", 0, 16)); // NOI18N
        AnsFacebook.setText(" ");
        getContentPane().add(AnsFacebook, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 320, 300, -1));
        AnsFacebook.setText(Students.getStd_facebook(stdID));

        แพ้ยาอะไร.setFont(new java.awt.Font("Quark", 1, 16)); // NOI18N
        แพ้ยาอะไร.setText("แพ้ยาอะไร :");
        getContentPane().add(แพ้ยาอะไร, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 350, -1, -1));

        AnsMedicine.setFont(new java.awt.Font("Quark", 0, 16)); // NOI18N
        AnsMedicine.setText(" ");
        getContentPane().add(AnsMedicine, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 350, 80, -1));
        AnsMedicine.setText(Students.getStd_medicine(stdID));

        แพ้อาหาอะไร.setFont(new java.awt.Font("Quark", 1, 16)); // NOI18N
        แพ้อาหาอะไร.setText("แพ้อาหารอะไร :");
        getContentPane().add(แพ้อาหาอะไร, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 380, -1, -1));

        AnsFood.setFont(new java.awt.Font("Quark", 0, 16)); // NOI18N
        AnsFood.setText(" ");
        getContentPane().add(AnsFood, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 380, 170, -1));
        AnsFood.setText(Students.getStd_food(stdID));

        Email.setFont(new java.awt.Font("Quark", 1, 16)); // NOI18N
        Email.setText("E-mail :");
        getContentPane().add(Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 410, -1, -1));

        AnsEmail.setFont(new java.awt.Font("Quark", 0, 16)); // NOI18N
        AnsEmail.setText(" ");
        getContentPane().add(AnsEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 410, 240, -1));
        AnsEmail.setText(Students.getStd_email(stdID));

        ID.setFont(new java.awt.Font("Quark", 0, 18)); // NOI18N
        ID.setText("ID :");
        getContentPane().add(ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 70, 40, 30));

        ShowID.setFont(new java.awt.Font("Quark", 0, 18)); // NOI18N
        getContentPane().add(ShowID, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 70, 220, 30));
        ShowID.setText(stdID+"");

        Edit.setBackground(new java.awt.Color(255, 51, 0));
        Edit.setFont(new java.awt.Font("Quark", 0, 18)); // NOI18N
        Edit.setForeground(new java.awt.Color(255, 255, 255));
        Edit.setText("EDIT");
        Edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditActionPerformed(evt);
            }
        });
        getContentPane().add(Edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 530, 92, 50));

        Confirm.setBackground(new java.awt.Color(255, 51, 0));
        Confirm.setFont(new java.awt.Font("Quark", 0, 18)); // NOI18N
        Confirm.setForeground(new java.awt.Color(255, 255, 255));
        Confirm.setText("CONFIRM");
        Confirm.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Confirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmActionPerformed(evt);
            }
        });
        getContentPane().add(Confirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 530, 150, 50));

        blackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Confirmation.png"))); // NOI18N
        getContentPane().add(blackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -80, 1030, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditActionPerformed
       ViewProfile view = new ViewProfile();
       this.setVisible(false);
       view.setVisible(true);
    }//GEN-LAST:event_EditActionPerformed

    private void ConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmActionPerformed
       Done d = new Done();
       this.setVisible(false);
       d.setVisible(true);
    }//GEN-LAST:event_ConfirmActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewRegist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewRegist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewRegist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewRegist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewRegist().setVisible(true);
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AnsEmail;
    private javax.swing.JLabel AnsFacebook;
    private javax.swing.JLabel AnsFood;
    private javax.swing.JLabel AnsMedicine;
    private javax.swing.JLabel AnsName;
    private javax.swing.JLabel AnsTelephone;
    private javax.swing.JLabel ClubID;
    private javax.swing.JButton Confirm;
    private javax.swing.JButton Edit;
    private javax.swing.JLabel Email;
    private javax.swing.JLabel Facebook;
    private javax.swing.JLabel ID;
    private javax.swing.JLabel Name;
    private javax.swing.JLabel NameClub;
    private javax.swing.JLabel ShowClubID;
    private javax.swing.JLabel ShowID;
    private javax.swing.JLabel Telephone;
    private javax.swing.JLabel blackground;
    private javax.swing.JLabel pic;
    private javax.swing.JLabel เส้นขีดเฉยๆ;
    private javax.swing.JLabel แพ้ยาอะไร;
    private javax.swing.JLabel แพ้อาหาอะไร;
    // End of variables declaration//GEN-END:variables
}
