/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package publicregistergroup.view;

/**
 *
 * @author kz_no
 */
public class ViewRegist extends javax.swing.JFrame {

    /**
     * Creates new form ViewRegist
     */
    public ViewRegist() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        NameClub = new javax.swing.JLabel();
        ClubID = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pic = new javax.swing.JLabel();
        Name = new javax.swing.JLabel();
        Surname = new javax.swing.JLabel();
        Telephone = new javax.swing.JLabel();
        Facebook = new javax.swing.JLabel();
        Email = new javax.swing.JLabel();
        แพ้ยาอะไร = new javax.swing.JLabel();
        แพ้อาหาอะไร = new javax.swing.JLabel();
        AnsName = new javax.swing.JLabel();
        AnsSurname = new javax.swing.JLabel();
        AnsTelephone = new javax.swing.JLabel();
        AnsFacebook = new javax.swing.JLabel();
        Ansแพ้ยาอะไร = new javax.swing.JLabel();
        Ansแพ้อาหารอะไร = new javax.swing.JLabel();
        AnsEmail = new javax.swing.JLabel();
        Confirm = new javax.swing.JButton();
        Edit = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        Bottonsearch1 = new javax.swing.JButton();
        blackground = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        NameClub1 = new javax.swing.JLabel();
        ClubID1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        pic1 = new javax.swing.JLabel();
        Name1 = new javax.swing.JLabel();
        Surname1 = new javax.swing.JLabel();
        Telephone1 = new javax.swing.JLabel();
        Facebook1 = new javax.swing.JLabel();
        Email1 = new javax.swing.JLabel();
        แพ้ยาอะไร1 = new javax.swing.JLabel();
        แพ้อาหาอะไร1 = new javax.swing.JLabel();
        AnsName1 = new javax.swing.JLabel();
        AnsSurname1 = new javax.swing.JLabel();
        AnsTelephone1 = new javax.swing.JLabel();
        AnsFacebook1 = new javax.swing.JLabel();
        Ansแพ้ยาอะไร1 = new javax.swing.JLabel();
        Ansแพ้อาหารอะไร1 = new javax.swing.JLabel();
        AnsEmail1 = new javax.swing.JLabel();
        Confirm1 = new javax.swing.JButton();
        Edit1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1024, 768));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        NameClub.setFont(new java.awt.Font("Quark", 1, 32)); // NOI18N
        NameClub.setText("ชมรมอาสาพัฒนาชุมชน");

        ClubID.setFont(new java.awt.Font("Quark", 0, 14)); // NOI18N
        ClubID.setText("CLUB ID : ");

        jLabel2.setText("____________________________________________________________________________________________________________________");

        pic.setFont(new java.awt.Font("Quark", 1, 72)); // NOI18N
        pic.setForeground(new java.awt.Color(153, 153, 153));
        pic.setText("    PIC");
        pic.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        Name.setFont(new java.awt.Font("Quark", 1, 18)); // NOI18N
        Name.setText("Name :");

        Surname.setFont(new java.awt.Font("Quark", 1, 18)); // NOI18N
        Surname.setText("Surname :");

        Telephone.setFont(new java.awt.Font("Quark", 1, 18)); // NOI18N
        Telephone.setText("Telephone :");

        Facebook.setFont(new java.awt.Font("Quark", 1, 18)); // NOI18N
        Facebook.setText("Facebook :");

        Email.setFont(new java.awt.Font("Quark", 1, 18)); // NOI18N
        Email.setText("E-mail :");

        แพ้ยาอะไร.setFont(new java.awt.Font("Quark", 1, 18)); // NOI18N
        แพ้ยาอะไร.setText("แพ้ยาอะไร :");

        แพ้อาหาอะไร.setFont(new java.awt.Font("Quark", 1, 18)); // NOI18N
        แพ้อาหาอะไร.setText("แพ้อาหารอะไร :");

        AnsName.setFont(new java.awt.Font("Quark", 0, 18)); // NOI18N
        AnsName.setText("Kittiya ");

        AnsSurname.setFont(new java.awt.Font("Quark", 0, 18)); // NOI18N
        AnsSurname.setText("Yuthasastrkosol");

        AnsTelephone.setFont(new java.awt.Font("Quark", 0, 18)); // NOI18N
        AnsTelephone.setText("090-7700443");

        AnsFacebook.setFont(new java.awt.Font("Quark", 0, 18)); // NOI18N
        AnsFacebook.setText("Noey Kittiya");

        Ansแพ้ยาอะไร.setFont(new java.awt.Font("Quark", 0, 18)); // NOI18N
        Ansแพ้ยาอะไร.setText("-");

        Ansแพ้อาหารอะไร.setFont(new java.awt.Font("Quark", 0, 18)); // NOI18N
        Ansแพ้อาหารอะไร.setText("-");

        AnsEmail.setFont(new java.awt.Font("Quark", 0, 18)); // NOI18N
        AnsEmail.setText("kz_noey@hotmail.com");

        Confirm.setFont(new java.awt.Font("Quark", 0, 14)); // NOI18N
        Confirm.setText("CONFIRM");

        Edit.setFont(new java.awt.Font("Quark", 0, 10)); // NOI18N
        Edit.setText("EDIT");
        Edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(186, 186, 186)
                        .addComponent(pic, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(Edit))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Name)
                                .addGap(18, 18, 18)
                                .addComponent(AnsName))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Surname)
                                .addGap(18, 18, 18)
                                .addComponent(AnsSurname))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Telephone)
                                .addGap(18, 18, 18)
                                .addComponent(AnsTelephone))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Facebook)
                                .addGap(18, 18, 18)
                                .addComponent(AnsFacebook))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(แพ้ยาอะไร)
                                .addGap(18, 18, 18)
                                .addComponent(Ansแพ้ยาอะไร))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(แพ้อาหาอะไร)
                                .addGap(18, 18, 18)
                                .addComponent(Ansแพ้อาหารอะไร))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Email)
                                .addGap(18, 18, 18)
                                .addComponent(AnsEmail))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(219, 219, 219)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ClubID)
                            .addComponent(NameClub))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 136, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(128, 128, 128))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(Confirm, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(153, 153, 153))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(NameClub)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(ClubID)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(pic, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Name)
                            .addComponent(AnsName))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Surname)
                            .addComponent(AnsSurname))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Telephone)
                            .addComponent(AnsTelephone))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Facebook)
                            .addComponent(AnsFacebook))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(แพ้ยาอะไร)
                            .addComponent(Ansแพ้ยาอะไร))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(แพ้อาหาอะไร)
                            .addComponent(Ansแพ้อาหารอะไร))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Email)
                            .addComponent(AnsEmail))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Edit)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Confirm, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 90, 261, 22));

        Bottonsearch1.setFont(new java.awt.Font("Kanit", 0, 13)); // NOI18N
        Bottonsearch1.setText("OK");
        Bottonsearch1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bottonsearch1ActionPerformed(evt);
            }
        });
        getContentPane().add(Bottonsearch1, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 88, 80, 25));

        blackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/page.jpg"))); // NOI18N
        blackground.setText("jLabel1");
        getContentPane().add(blackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 770));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        NameClub1.setFont(new java.awt.Font("Quark", 1, 32)); // NOI18N
        NameClub1.setText("ชมรมอาสาพัฒนาชุมชน");

        ClubID1.setFont(new java.awt.Font("Quark", 0, 14)); // NOI18N
        ClubID1.setText("CLUB ID : ");

        jLabel3.setText("____________________________________________________________________________________________________________________");

        pic1.setFont(new java.awt.Font("Quark", 1, 72)); // NOI18N
        pic1.setForeground(new java.awt.Color(153, 153, 153));
        pic1.setText("    PIC");
        pic1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        Name1.setFont(new java.awt.Font("Quark", 1, 18)); // NOI18N
        Name1.setText("Name :");

        Surname1.setFont(new java.awt.Font("Quark", 1, 18)); // NOI18N
        Surname1.setText("Surname :");

        Telephone1.setFont(new java.awt.Font("Quark", 1, 18)); // NOI18N
        Telephone1.setText("Telephone :");

        Facebook1.setFont(new java.awt.Font("Quark", 1, 18)); // NOI18N
        Facebook1.setText("Facebook :");

        Email1.setFont(new java.awt.Font("Quark", 1, 18)); // NOI18N
        Email1.setText("E-mail :");

        แพ้ยาอะไร1.setFont(new java.awt.Font("Quark", 1, 18)); // NOI18N
        แพ้ยาอะไร1.setText("แพ้ยาอะไร :");

        แพ้อาหาอะไร1.setFont(new java.awt.Font("Quark", 1, 18)); // NOI18N
        แพ้อาหาอะไร1.setText("แพ้อาหารอะไร :");

        AnsName1.setFont(new java.awt.Font("Quark", 0, 18)); // NOI18N
        AnsName1.setText("Kittiya ");

        AnsSurname1.setFont(new java.awt.Font("Quark", 0, 18)); // NOI18N
        AnsSurname1.setText("Yuthasastrkosol");

        AnsTelephone1.setFont(new java.awt.Font("Quark", 0, 18)); // NOI18N
        AnsTelephone1.setText("090-7700443");

        AnsFacebook1.setFont(new java.awt.Font("Quark", 0, 18)); // NOI18N
        AnsFacebook1.setText("Noey Kittiya");

        Ansแพ้ยาอะไร1.setFont(new java.awt.Font("Quark", 0, 18)); // NOI18N
        Ansแพ้ยาอะไร1.setText("-");

        Ansแพ้อาหารอะไร1.setFont(new java.awt.Font("Quark", 0, 18)); // NOI18N
        Ansแพ้อาหารอะไร1.setText("-");

        AnsEmail1.setFont(new java.awt.Font("Quark", 0, 18)); // NOI18N
        AnsEmail1.setText("kz_noey@hotmail.com");

        Confirm1.setFont(new java.awt.Font("Quark", 0, 14)); // NOI18N
        Confirm1.setText("CONFIRM");

        Edit1.setFont(new java.awt.Font("Quark", 0, 10)); // NOI18N
        Edit1.setText("EDIT");
        Edit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Edit1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(186, 186, 186)
                        .addComponent(pic1, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(Edit1))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(Name1)
                                .addGap(18, 18, 18)
                                .addComponent(AnsName1))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(Surname1)
                                .addGap(18, 18, 18)
                                .addComponent(AnsSurname1))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(Telephone1)
                                .addGap(18, 18, 18)
                                .addComponent(AnsTelephone1))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(Facebook1)
                                .addGap(18, 18, 18)
                                .addComponent(AnsFacebook1))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(แพ้ยาอะไร1)
                                .addGap(18, 18, 18)
                                .addComponent(Ansแพ้ยาอะไร1))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(แพ้อาหาอะไร1)
                                .addGap(18, 18, 18)
                                .addComponent(Ansแพ้อาหารอะไร1))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(Email1)
                                .addGap(18, 18, 18)
                                .addComponent(AnsEmail1))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(219, 219, 219)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ClubID1)
                            .addComponent(NameClub1))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 136, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(128, 128, 128))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(Confirm1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(153, 153, 153))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(NameClub1)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(ClubID1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(pic1, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Name1)
                            .addComponent(AnsName1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Surname1)
                            .addComponent(AnsSurname1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Telephone1)
                            .addComponent(AnsTelephone1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Facebook1)
                            .addComponent(AnsFacebook1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(แพ้ยาอะไร1)
                            .addComponent(Ansแพ้ยาอะไร1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(แพ้อาหาอะไร1)
                            .addComponent(Ansแพ้อาหารอะไร1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Email1)
                            .addComponent(AnsEmail1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Edit1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Confirm1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void Bottonsearch1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bottonsearch1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Bottonsearch1ActionPerformed

    private void EditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditActionPerformed
       ViewProfile view = new ViewProfile();
       this.setVisible(false);
       view.setVisible(true);
    }//GEN-LAST:event_EditActionPerformed

    private void Edit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Edit1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Edit1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewRegist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewRegist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewRegist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewRegist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewRegist().setVisible(true);
                jPanel1.setOpaque(false);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AnsEmail;
    private javax.swing.JLabel AnsEmail1;
    private javax.swing.JLabel AnsFacebook;
    private javax.swing.JLabel AnsFacebook1;
    private javax.swing.JLabel AnsName;
    private javax.swing.JLabel AnsName1;
    private javax.swing.JLabel AnsSurname;
    private javax.swing.JLabel AnsSurname1;
    private javax.swing.JLabel AnsTelephone;
    private javax.swing.JLabel AnsTelephone1;
    private javax.swing.JLabel Ansแพ้ยาอะไร;
    private javax.swing.JLabel Ansแพ้ยาอะไร1;
    private javax.swing.JLabel Ansแพ้อาหารอะไร;
    private javax.swing.JLabel Ansแพ้อาหารอะไร1;
    private javax.swing.JButton Bottonsearch1;
    private javax.swing.JLabel ClubID;
    private javax.swing.JLabel ClubID1;
    private javax.swing.JButton Confirm;
    private javax.swing.JButton Confirm1;
    private javax.swing.JButton Edit;
    private javax.swing.JButton Edit1;
    private javax.swing.JLabel Email;
    private javax.swing.JLabel Email1;
    private javax.swing.JLabel Facebook;
    private javax.swing.JLabel Facebook1;
    private javax.swing.JLabel Name;
    private javax.swing.JLabel Name1;
    private javax.swing.JLabel NameClub;
    private javax.swing.JLabel NameClub1;
    private javax.swing.JLabel Surname;
    private javax.swing.JLabel Surname1;
    private javax.swing.JLabel Telephone;
    private javax.swing.JLabel Telephone1;
    private javax.swing.JLabel blackground;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    protected static javax.swing.JPanel jPanel1;
    private static javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel pic;
    private javax.swing.JLabel pic1;
    private javax.swing.JLabel แพ้ยาอะไร;
    private javax.swing.JLabel แพ้ยาอะไร1;
    private javax.swing.JLabel แพ้อาหาอะไร;
    private javax.swing.JLabel แพ้อาหาอะไร1;
    // End of variables declaration//GEN-END:variables
}
