/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package publicregistergroup.model;

/**
 *
 * @author taloey
 */
public class LinkData extends javax.swing.JFrame {

    /**
     * Creates new form Uploadphoto
     */
    public LinkData() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textsearchclub = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        Bottonsearch = new javax.swing.JButton();
        Title = new javax.swing.JLabel();
        UsernameID = new javax.swing.JLabel();
        Box1 = new javax.swing.JPanel();
        changeprofilebotton = new javax.swing.JButton();
        Box2 = new javax.swing.JPanel();
        checkclubbotton = new javax.swing.JButton();
        Box3 = new javax.swing.JPanel();
        clubbotton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        blackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        textsearchclub.setFont(new java.awt.Font("Quark", 0, 14)); // NOI18N
        textsearchclub.setText("serach from club or organize for you interest");
        getContentPane().add(textsearchclub, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 290, 20));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 300, 30));

        Bottonsearch.setFont(new java.awt.Font("Kanit", 0, 13)); // NOI18N
        Bottonsearch.setText("OK");
        Bottonsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BottonsearchActionPerformed(evt);
            }
        });
        getContentPane().add(Bottonsearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 100, 80, 30));

        Title.setFont(new java.awt.Font("Kailasa", 0, 36)); // NOI18N
        Title.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logo.png"))); // NOI18N
        getContentPane().add(Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 440, 50));

        UsernameID.setFont(new java.awt.Font("Kanit", 0, 24)); // NOI18N
        getContentPane().add(UsernameID, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 40, 220, 30));

        Box1.setBackground(new java.awt.Color(77, 77, 77));
        Box1.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(205, 77, 40)));

        changeprofilebotton.setFont(new java.awt.Font("Quark", 0, 48)); // NOI18N
        changeprofilebotton.setForeground(new java.awt.Color(204, 204, 204));
        changeprofilebotton.setText("แก้ไขข้อมูลส่วนตัว");
        changeprofilebotton.setBorder(null);
        changeprofilebotton.setContentAreaFilled(false);
        changeprofilebotton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        changeprofilebotton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeprofilebottonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Box1Layout = new javax.swing.GroupLayout(Box1);
        Box1.setLayout(Box1Layout);
        Box1Layout.setHorizontalGroup(
            Box1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Box1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(changeprofilebotton)
                .addContainerGap(37, Short.MAX_VALUE))
        );
        Box1Layout.setVerticalGroup(
            Box1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Box1Layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(changeprofilebotton)
                .addContainerGap(93, Short.MAX_VALUE))
        );

        getContentPane().add(Box1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 330, 270));

        Box2.setBackground(new java.awt.Color(77, 77, 77));
        Box2.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(205, 77, 40)));

        checkclubbotton.setFont(new java.awt.Font("Quark", 0, 36)); // NOI18N
        checkclubbotton.setForeground(new java.awt.Color(204, 204, 204));
        checkclubbotton.setText("เช็ค club activities");
        checkclubbotton.setBorder(null);
        checkclubbotton.setContentAreaFilled(false);
        checkclubbotton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        checkclubbotton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkclubbottonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Box2Layout = new javax.swing.GroupLayout(Box2);
        Box2.setLayout(Box2Layout);
        Box2Layout.setHorizontalGroup(
            Box2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Box2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(checkclubbotton, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        Box2Layout.setVerticalGroup(
            Box2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Box2Layout.createSequentialGroup()
                .addContainerGap(110, Short.MAX_VALUE)
                .addComponent(checkclubbotton)
                .addGap(103, 103, 103))
        );

        getContentPane().add(Box2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 270, 340, 270));

        Box3.setBackground(new java.awt.Color(77, 77, 77));
        Box3.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(205, 77, 40)));

        clubbotton.setFont(new java.awt.Font("Quark", 0, 48)); // NOI18N
        clubbotton.setForeground(new java.awt.Color(204, 204, 204));
        clubbotton.setText("ดูข้อมูลชมรม");
        clubbotton.setBorder(null);
        clubbotton.setContentAreaFilled(false);
        clubbotton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        clubbotton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clubbottonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Box3Layout = new javax.swing.GroupLayout(Box3);
        Box3.setLayout(Box3Layout);
        Box3Layout.setHorizontalGroup(
            Box3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Box3Layout.createSequentialGroup()
                .addContainerGap(79, Short.MAX_VALUE)
                .addComponent(clubbotton)
                .addGap(54, 54, 54))
        );
        Box3Layout.setVerticalGroup(
            Box3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Box3Layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(clubbotton)
                .addContainerGap(92, Short.MAX_VALUE))
        );

        getContentPane().add(Box3, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 270, 330, 270));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logo.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 640, -1, 40));

        jLabel3.setFont(new java.awt.Font("Quark", 0, 14)); // NOI18N
        jLabel3.setText("KMUTT 126 Pracha Uthit Rd, Khwaeng Bang Mot");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 680, -1, 20));

        jLabel4.setFont(new java.awt.Font("Quark", 0, 14)); // NOI18N
        jLabel4.setText("Khet Thung Khru, Krung Thep Maha Nakhon 10140");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 700, -1, -1));

        jLabel5.setFont(new java.awt.Font("Quark", 0, 14)); // NOI18N
        jLabel5.setText("© Copyright 2017 KMUTT PublicizeHUB");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 720, -1, -1));

        blackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/background.png"))); // NOI18N
        blackground.setText("jLabel1");
        getContentPane().add(blackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(-5, 0, 1030, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BottonsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BottonsearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BottonsearchActionPerformed

    private void checkclubbottonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkclubbottonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkclubbottonActionPerformed

    private void clubbottonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clubbottonActionPerformed
        Uploadphoto upload = new Uploadphoto();
       this.setVisible(false);
       upload.setVisible(true);
    }//GEN-LAST:event_clubbottonActionPerformed

    private void changeprofilebottonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeprofilebottonActionPerformed
      ViewProfile profile = new ViewProfile();
       this.setVisible(false);
       profile.setVisible(true);
    }//GEN-LAST:event_changeprofilebottonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LinkData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LinkData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LinkData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LinkData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LinkData().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bottonsearch;
    private javax.swing.JPanel Box1;
    private javax.swing.JPanel Box2;
    private javax.swing.JPanel Box3;
    private javax.swing.JLabel Title;
    private javax.swing.JLabel UsernameID;
    private javax.swing.JLabel blackground;
    private javax.swing.JButton changeprofilebotton;
    private javax.swing.JButton checkclubbotton;
    private javax.swing.JButton clubbotton;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel textsearchclub;
    // End of variables declaration//GEN-END:variables
}
